name: Flutter Web Build

on:
  push:
    branches:
      - main  # Ou la branche que tu veux suivre
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      # use this if you need generate build_runner related files
      - run: dart run build_runner build --delete-conflicting-outputs
      - run: flutter build web --source-maps --web-renderer=canvaskit

    - name: Upload Web Build as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: web-build
        path: build/web
